apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.baserow.backendConfigMap }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "2"
  labels:
    {{- include "baserow.labels" . | nindent 4 }}
data:
  {{ toYaml .Values.backendConfigMap | nindent 2 }}
  DATABASE_USER: {{ include "baserow.postgresql.username" . | quote }}
