apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.baserow.frontendConfigMap }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "baserow.labels" . | nindent 4 }}
data: {{ toYaml .Values.frontendConfigMap | nindent 2 }}
